registry: "gcr.io/datadoghq"

targetSystem: "linux"

datadog:
  clusterName: "vitor-m"
  apiKeyExistingSecret: "datadog-secret"
  site: "datadoghq.com"
  tags:
    - "env:prod"

  # Process collection
  processAgent:
    enabled: true
    processCollection: true

  # Logs collection
  logs:
    enabled: true
    containerCollectAll: false

  agents:
    daemonset:
      affinity:
      podAntiAffinity: {}

  # Orchestrator Explorer
  orchestratorExplorer:
    enabled: true

  # APM Configuration
  apm:
    portEnabled: true
    
  clusterAgent:
    enabled: true
    admissionController:
      enabled: true
      configMode: service
      mutateUnlabelled: true
    confd:
      postgres.yaml: |-
        cluster_check: true
        init_config:
        instances:
          - dbm: true
            host: <AZURE_INSTANCE_ENDPOINT>
            port: 5432
            username: 'datadog@<AZURE_INSTANCE_ENDPOINT>'
            password: 'ENC[datadog_user_database_password]'
            ssl: 'require'
            azure:
              deployment_type: '<DEPLOYMENT_TYPE>'
              fully_qualified_domain_name: '<AZURE_INSTANCE_ENDPOINT>' 